import * as THREE from 'three';
import { TargetDummy } from '../target/TargetDummy';

type KillMethod='MELEE'|'SHOT'|'GRAPPLE';
export class TutorialSystem {
  step=0; movement=new Set<string>(); jumped=false; grappleUsed=false; grappleCancelled=false; rings:THREE.Mesh[]=[]; ringPassed:boolean[]=[]; active=false;
  panel=document.createElement('section'); banner=document.createElement('div'); prompt=document.createElement('div'); promptTimer=0;
  constructor(private scene:THREE.Scene,private dummy:TargetDummy,private onComplete:()=>void,private onCheck:()=>void){this.panel.id='mission';this.banner.id='mission-banner';this.prompt.id='mission-prompt';document.body.append(this.panel,this.banner,this.prompt);this.hide();}
  start(){this.active=true;this.step=0;this.movement.clear();this.jumped=false;this.grappleUsed=false;this.grappleCancelled=false;this.clearRings();this.dummy.kill();this.panel.style.display='block';this.render();this.showPrompt();}
  hide(){this.active=false;this.panel.style.display='none';this.banner.style.display='none';this.prompt.style.display='none';this.clearRings();}
  key(code:string){if(!this.active||this.step!==0)return;const moved=this.movement.size===4,jumped=this.jumped;if(['KeyW','KeyA','KeyS','KeyD'].includes(code))this.movement.add(code);if(code==='Space')this.jumped=true;if(!moved&&this.movement.size===4)this.onCheck();if(!jumped&&this.jumped)this.onCheck();this.render();if(this.movement.size===4&&this.jumped)this.advance();}
  grappleAttached(){if(this.active&&this.step===3&&!this.grappleUsed){this.grappleUsed=true;this.onCheck();this.render();this.checkGrappleStep();}}
  grappleReleased(){if(this.active&&this.step===3&&!this.grappleCancelled){this.grappleCancelled=true;this.onCheck();this.render();this.checkGrappleStep();}}
  dummyKilled(method:KillMethod,airborneGrapple:boolean){if(!this.active)return;if(this.step===1&&method==='MELEE'){this.onCheck();this.advance();}else if(this.step===2&&method==='SHOT'){this.onCheck();this.advance();}else if(this.step===4&&method==='SHOT'&&airborneGrapple){this.onCheck();this.advance();}}
  update(pos:THREE.Vector3,dt:number){if(!this.active)return;if(this.promptTimer>0){this.promptTimer-=dt;if(this.promptTimer<=0)this.prompt.style.display='none';}if(this.step!==3)return;this.rings.forEach((ring,i)=>{if(!this.ringPassed[i]&&ring.position.distanceTo(pos)<2.15){this.ringPassed[i]=true;this.onCheck();(ring.material as THREE.MeshBasicMaterial).color.set(0x38e784);}});this.render();this.checkGrappleStep();}
  checkGrappleStep(){if(this.step===3&&this.grappleUsed&&this.grappleCancelled&&this.ringPassed.length===3&&this.ringPassed.every(Boolean))this.advance();}
  advance(){this.flash('MISSION COMPLETE');this.step++;if(this.step===1){this.dummy.group.position.set(0,0,3);this.dummy.reset();}else if(this.step===2){this.dummy.group.position.set(0,0,-18);this.dummy.reset();}else if(this.step===3){this.dummy.kill();this.grappleUsed=false;this.grappleCancelled=false;this.spawnRings();}else if(this.step===4){this.clearRings();this.dummy.group.position.set(0,0,-18);this.dummy.reset();}else if(this.step>=5){this.panel.style.display='none';setTimeout(()=>{this.hide();this.onComplete();},1000);}this.render();if(this.step<5)this.showPrompt();}
  spawnRings(){const positions=[new THREE.Vector3(7,5,-16),new THREE.Vector3(15,9,-10),new THREE.Vector3(12,12,6)];this.ringPassed=positions.map(()=>false);for(const pos of positions){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.75,.16,12,36),new THREE.MeshBasicMaterial({color:0xef3e52,side:THREE.DoubleSide}));ring.position.copy(pos);ring.rotation.y=Math.PI/2;this.scene.add(ring);this.rings.push(ring);}}
  clearRings(){for(const ring of this.rings){this.scene.remove(ring);ring.geometry.dispose();(ring.material as THREE.Material).dispose();}this.rings=[];this.ringPassed=[];}
  flash(text:string){this.banner.textContent=`✓ ${text}`;this.banner.style.display='block';setTimeout(()=>this.banner.style.display='none',850);}
  showPrompt(){const messages=['WASD로 이동하고 Space로 점프하세요','가까운 더미를 근접 공격으로 처치하세요','현재 위치에서 줌 사격으로 원거리 더미를 처치하세요','그래플과 Space 해제를 사용해 링 3개를 통과하세요','그래플 비행 중 줌 사격으로 더미를 처치하세요'];this.prompt.textContent=messages[this.step]??'';this.prompt.style.display='block';this.promptTimer=3;}
  check(done:boolean,label:string){return `<li class="${done?'done':''}"><i>${done?'✓':'□'}</i><span>${label}</span></li>`;}
  render(){if(!this.active)return;let title='',items='';if(this.step===0){title='기본 이동';items=this.check(this.movement.size===4,'W · A · S · D 모두 사용')+this.check(this.jumped,'Space로 점프');}else if(this.step===1){title='근접 공격';items=this.check(false,'더미에 가까이 가서 좌클릭으로 근접 처치');}else if(this.step===2){title='정밀 사격';items=this.check(false,'현재 위치에서 원거리 더미를 줌 사격');}else if(this.step===3){title='그래플 코스';items=this.check(this.grappleUsed,'Shift로 그래플 부착')+this.check(this.grappleCancelled,'비행 중 Space로 그래플 해제')+this.ringPassed.map((v,i)=>this.check(v,`공중 링 ${i+1} 통과`)).join('');}else if(this.step===4){title='공중 사격';items=this.check(false,'그래플로 공중에 뜬 상태에서 더미 처치');}this.panel.innerHTML=`<small>TUTORIAL ${Math.min(this.step+1,5)} / 5</small><h2>${title}</h2><ul>${items}</ul>`;}
}
