import * as THREE from 'three';import { Stage2Map } from './Stage2Map';import { STAGE2,STAGE2_TARGETS } from './Stage2Config';import { Stage2Target } from '../target/Stage2Target';import { Stage2RunStats,Stage2HitType } from '../scoring/Stage2RunStats';import { Stage2UI } from '../ui/Stage2UI';
import { CFG } from '../core/GameConfig';
import type { Stage2Record } from '../core/Persistence';
export type Stage2State='INACTIVE'|'INTRO'|'PLAYING'|'CLEAR';
export interface Stage2Callbacks{lock:()=>Promise<boolean>;intro:(continueStart:()=>void)=>void;respawn:()=>void;started:()=>void;cleared:(record:Stage2Record)=>void;back:()=>void;next:()=>void;fell:()=>void;}
export class Stage2{
  map:Stage2Map;targets:Stage2Target[];stats=new Stage2RunStats();ui=new Stage2UI();state:Stage2State='INACTIVE';startTime=0;pauseStartedAt:number|null=null;pausedDuration=0;lastPosition=STAGE2.start.clone();lastGoalNoticeAt=-Infinity;
  constructor(scene:THREE.Scene,private callbacks:Stage2Callbacks){this.map=new Stage2Map(scene);this.targets=STAGE2_TARGETS.map(d=>new Stage2Target(d.id,new THREE.Vector3(...d.position),scene));this.targets.forEach(t=>t.setVisible(false));this.ui.bind(()=>void this.begin(),()=>this.enter(),callbacks.back,callbacks.next);}
  enter(){this.state='INTRO';this.stats.reset();this.pauseStartedAt=null;this.pausedDuration=0;this.lastGoalNoticeAt=-Infinity;this.map.setVisible(true);for(const t of this.targets){t.reset();t.setVisible(true);}this.lastPosition.copy(STAGE2.start);this.callbacks.respawn();this.ui.showIntro();this.ui.updateHUD(0,0,0);}
  begin(){if(this.state!=='INTRO')return;this.ui.hideAll();this.callbacks.intro(()=>void this.startAfterIntro());}
  async startAfterIntro(){if(this.state!=='INTRO')return;const locked=await this.callbacks.lock();if(!locked){this.ui.showIntro();return;}this.state='PLAYING';this.startTime=performance.now();this.pauseStartedAt=null;this.pausedDuration=0;this.lastPosition.copy(STAGE2.start);this.ui.showHUD();this.callbacks.started();}
  update(position:THREE.Vector3,paused=false){if(this.state!=='PLAYING')return;const now=performance.now();if(paused){if(this.pauseStartedAt===null)this.pauseStartedAt=now;this.stats.elapsedTime=(this.pauseStartedAt-this.startTime-this.pausedDuration)/1000;this.ui.updateHUD(this.stats.elapsedTime,this.stats.targetsDestroyed,this.stats.targetScore);return;}if(this.pauseStartedAt!==null){this.pausedDuration+=now-this.pauseStartedAt;this.pauseStartedAt=null;this.lastPosition.copy(position);}this.stats.elapsedTime=(now-this.startTime-this.pausedDuration)/1000;this.ui.updateHUD(this.stats.elapsedTime,this.stats.targetsDestroyed,this.stats.targetScore);for(const target of this.targets){const d=target.center().distanceTo(position);target.setHighlight(target.alive&&d<=STAGE2.highlightRange);}const feetY=position.y-CFG.eyeHeight;if(feetY<=STAGE2.deathFloorY+.02||position.y<STAGE2.fallY){this.callbacks.fell();this.callbacks.respawn();this.ui.respawn();this.lastPosition.copy(STAGE2.start);return;}if(this.segmentHitsGoal(this.lastPosition,position)){if(this.stats.targetsDestroyed>=STAGE2.minKillsToClear)this.clear();else if(now-this.lastGoalNoticeAt>=1400){this.lastGoalNoticeAt=now;this.ui.notice(`클리어하려면 과녁을 ${STAGE2.minKillsToClear}개 이상 처치하세요 (${this.stats.targetsDestroyed}/${STAGE2.minKillsToClear})`);}}this.lastPosition.copy(position);}
  segmentHitsGoal(a:THREE.Vector3,b:THREE.Vector3){const center=STAGE2.goal,t=b.clone().sub(a),len2=t.lengthSq();const u=len2?THREE.MathUtils.clamp(center.clone().sub(a).dot(t)/len2,0,1):0;return a.clone().addScaledVector(t,u).distanceTo(center)<=STAGE2.goalRadius;}
  hitObjects(){return this.targets.filter(t=>t.alive).flatMap(t=>t.hitObjects());}
  hitObject(object:THREE.Object3D,typeOverride?:Stage2HitType){const target=object.userData.stage2Target as Stage2Target|undefined;if(!target||!target.alive||this.state!=='PLAYING')return false;const type=typeOverride??'SHOT';if(!target.kill())return false;const score=this.stats.hit(type);this.ui.score(`TARGET +${score}`);return true;}
  melee(position:THREE.Vector3,forward:THREE.Vector3,range:number,halfAngle:number){let best:Stage2Target|undefined,bestD=Infinity;for(const t of this.targets){if(!t.alive)continue;const to=t.center().sub(position),d=to.length();to.y=0;if(d<range&&forward.angleTo(to.normalize())<halfAngle&&d<bestD){best=t;bestD=d;}}if(best)this.hitObject(best.body,'MELEE');}
  clear(){if(this.state!=='PLAYING')return;this.stats.elapsedTime=(performance.now()-this.startTime-this.pausedDuration)/1000;this.state='CLEAR';this.pauseStartedAt=null;for(const t of this.targets)t.setHighlight(false);const record:Stage2Record={score:this.stats.totalScore(),clearTime:this.stats.elapsedTime,kills:this.stats.targetsDestroyed,accuracy:this.stats.accuracy(),shotsFired:this.stats.shotsFired};this.ui.hideAll();this.callbacks.cleared(record);}
  leave(){this.state='INACTIVE';this.map.setVisible(false);for(const t of this.targets)t.setVisible(false);this.ui.hideAll();}
}
