import * as THREE from 'three';
import { CFG } from './GameConfig'; import { InputManager } from './InputManager';
import { TestArena } from '../world/TestArena'; import { TargetDummy } from '../target/TargetDummy'; import { DebugHUD } from '../ui/DebugHUD';
import { addStage2Record,addStage3Record,completeStage4,loadProgress,loadSettings,MOUSE_SENSITIVITY,saveProgress,ZOOM_SENSITIVITY,type Stage2Record } from './Persistence';
import { MenuUI } from '../ui/MenuUI'; import { TutorialSystem } from '../tutorial/TutorialSystem';
import { Stage2 } from '../stages/Stage2'; import { STAGE2 } from '../stages/Stage2Config'; import { BoxObstacle } from '../world/TestArena';
import { Stage3 } from '../stages/Stage3'; import { STAGE3 } from '../stages/Stage3Config';
import type { Stage3Result } from '../ui/Stage3UI';
import { SoundManager } from '../audio/SoundManager';
import { createTracerBeam,type TracerBeam } from '../visual/TracerBeam';
import { StorySystem,STORIES } from '../story/StorySystem';
import { Stage4,type Stage4Sound } from '../stages/Stage4'; import { STAGE4 } from '../stages/Stage4Config'; import type { Stage4Result } from '../ui/Stage4UI';
type GrappleState='READY'|'FIRING'|'PULLING'|'HOLDING'|'RELEASED'|'MISSED'|'ENEMY_HIT';
export class Game {
  renderer:THREE.WebGLRenderer; scene=new THREE.Scene(); camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,150);
  input:InputManager; arena:TestArena; dummy:TargetDummy; hud=new DebugHUD(); clock=new THREE.Clock(); ray=new THREE.Raycaster();
  pos=new THREE.Vector3(0,CFG.eyeHeight,8); vel=new THREE.Vector3(); yaw=0; pitch=0; grounded=false; fps=60; frames=0; fpsTime=0;
  grapple:GrappleState='READY'; hook:THREE.Mesh; rope:THREE.Line; hookStart=new THREE.Vector3(); hookDir=new THREE.Vector3(); grappleTarget=new THREE.Vector3(); grappleNormal=new THREE.Vector3(0,1,0); grappleHitObject:THREE.Object3D|null=null; grappleSurface='NONE'; grappleDistance=0; lastGrappleDistance=Infinity; grappleStallTime=0; pullElapsed=0; arrivalTime=0; autoHop=false; autoHopVerticalVelocity=0; grappleReleaseAscent=false;
  zoom=0;ammo=CFG.magazine;reloading=0;fireCd=0;melee=0;gun=new THREE.Group();meleeArm=new THREE.Group();gunMuzzle=new THREE.Object3D();gunRecoil=0;viewBob=0;tracers:{line:TracerBeam;life:number}[]=[];
  ammoEl=document.createElement('div'); grappleEl=document.createElement('div'); scope=document.createElement('div'); damageVignette=document.createElement('div');
  settings=loadSettings();sound=new SoundManager(()=>this.settings.sfx,()=>this.settings.bgm);story=new StorySystem(index=>this.sound.dialogueTick(index),()=>this.sound.dialogueAdvance());progress=loadProgress();menu:MenuUI;tutorial:TutorialSystem;stage2:Stage2;stage3:Stage3;stage4:Stage4;mode:'MENU'|'PLAYING'|'STAGE2_INTRO'|'STAGE2_PLAYING'|'STAGE2_CLEAR'|'STAGE3_INTRO'|'STAGE3_PLAYING'|'STAGE3_CLEAR'|'STAGE3_FAILED'|'STAGE4_INTRO'|'STAGE4_PLAYING'|'STAGE4_CLEAR'|'STAGE4_FAILED'='MENU';grappleAirborne=false;phase1Obstacles:BoxObstacle[];phase1GrappleMeshes:THREE.Object3D[];
  constructor(root:HTMLElement){
    this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;root.append(this.renderer.domElement);this.input=new InputManager(this.renderer.domElement);
    this.scene.background=new THREE.Color(0xd7d9dc);this.scene.fog=new THREE.Fog(0xd7d9dc,55,110);this.scene.add(new THREE.HemisphereLight(0xffffff,0x74787d,1.8));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(15,28,10);sun.castShadow=true;this.scene.add(sun);
    this.arena=new TestArena(this.scene);this.phase1Obstacles=this.arena.obstacles;this.phase1GrappleMeshes=this.arena.grappleMeshes;this.dummy=new TargetDummy(this.scene);this.camera.position.copy(this.pos);this.scene.add(this.camera);this.makeViewmodel();
    this.hook=new THREE.Mesh(new THREE.SphereGeometry(.12,10,7),new THREE.MeshBasicMaterial({color:0x55dcff}));this.hook.visible=false;this.scene.add(this.hook);this.rope=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0x62ddff}));this.rope.visible=false;this.scene.add(this.rope);
    document.body.insertAdjacentHTML('beforeend','<div class="cross"></div><div id="hint"><div><h1>PHASE 1 // HYPER FPS</h1><p>화면을 클릭해 전투 훈련 시작</p><p>WASD 이동 · Space 점프/그래플 해제 · Shift 그래플</p><p>우클릭 줌 · 좌클릭 사격/근접 · R 재장전 · Esc 해제</p><p class="lock-error"></p></div></div><button id="reset">더미 리셋 [T]</button>');
    document.body.insertAdjacentHTML('beforeend','<div id="pause-menu"><section><small>GAME PAUSED</small><h1>일시정지</h1><button id="continue-game">계속</button><button id="to-main-menu" class="secondary">메인 메뉴로</button></section></div>');
    this.scope.className='scope';this.damageVignette.id='damage-vignette';document.body.append(this.scope,this.damageVignette);this.ammoEl.className='ammo';this.grappleEl.className='grapple';document.body.append(this.ammoEl,this.grappleEl);
    document.querySelector('#hint')!.addEventListener('click',()=>this.input.lock());document.querySelector('#reset')!.addEventListener('click',()=>this.dummy.reset());
      this.tutorial=new TutorialSystem(this.scene,this.dummy,()=>this.completeTutorial(),()=>this.sound.missionSuccess());this.menu=new MenuUI(this.settings,this.progress,{tutorial:()=>this.storyTutorialIntro(),stage:s=>this.openStage(s)});this.stage2=new Stage2(this.scene,{lock:()=>this.input.lock(),intro:continueStart=>this.story.play(STORIES.stage2Intro,continueStart),respawn:()=>this.respawnStage2(),started:()=>this.mode='STAGE2_PLAYING',cleared:record=>this.stage2Cleared(record),back:()=>this.leaveStage2(),next:()=>this.advanceStage(2),fell:()=>this.sound.failure()});this.stage3=new Stage3(this.scene,this.camera,{lock:()=>this.input.lock(),intro:continueStart=>this.story.play(STORIES.stage3Intro,continueStart),respawn:()=>this.respawnStage3(),started:()=>this.mode='STAGE3_PLAYING',finished:result=>this.stage3Finished(result),back:()=>this.leaveStage3(),next:()=>this.advanceStage(3),fell:()=>this.sound.failure(),playerDamaged:()=>this.playerDamaged()});this.stage4=new Stage4(this.scene,{lock:()=>this.input.lock(),intro:continueStart=>this.story.play(STORIES.stage4Intro,continueStart),respawn:()=>this.respawnStage4(),started:()=>this.mode='STAGE4_PLAYING',finished:result=>this.stage4Finished(result),back:()=>this.leaveStage4(),next:()=>this.showStage4Thanks(),playerDamaged:()=>this.playerDamaged(),sound:cue=>this.stage4Sound(cue)});this.dummy.kill();document.querySelector('#continue-game')!.addEventListener('click',()=>this.input.lock());document.querySelector('#to-main-menu')!.addEventListener('click',()=>this.returnToMain());
    document.addEventListener('click',event=>{if((event.target as HTMLElement).closest('button'))this.sound.uiClick();});document.addEventListener('keydown',event=>{if(event.code==='Escape'&&!event.repeat)this.sound.escape();});document.addEventListener('input',event=>{const key=(event.target as HTMLInputElement).dataset.key;if(key==='sfx')this.sound.refreshSfxVolume();if(key==='bgm')this.sound.refreshBgmVolume();});document.addEventListener('change',event=>{const key=(event.target as HTMLInputElement).dataset.key;if(key==='sfx'||key==='bgm')this.sound.uiClick();});
    addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});this.loop();
  }
  makeViewmodel(){
    const body=new THREE.MeshStandardMaterial({color:0x202b34,metalness:.78,roughness:.24}),dark=new THREE.MeshStandardMaterial({color:0x0b1117,metalness:.55,roughness:.34}),steel=new THREE.MeshStandardMaterial({color:0x6e7c85,metalness:.9,roughness:.18}),accent=new THREE.MeshStandardMaterial({color:0x25b7da,emissive:0x063d4b,metalness:.55,roughness:.22}),lens=new THREE.MeshStandardMaterial({color:0x102f42,emissive:0x0b4259,metalness:.72,roughness:.08}),glove=new THREE.MeshStandardMaterial({color:0x17212a,metalness:.12,roughness:.58});
    const box=(size:[number,number,number],position:[number,number,number],material:THREE.Material,rotation:[number,number,number]=[0,0,0])=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),material);mesh.position.set(...position);mesh.rotation.set(...rotation);mesh.castShadow=true;this.gun.add(mesh);return mesh;};
    const cylinder=(radius:number,length:number,position:[number,number,number],material:THREE.Material,segments=12)=>{const mesh=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,length,segments),material);mesh.rotation.x=Math.PI/2;mesh.position.set(...position);mesh.castShadow=true;this.gun.add(mesh);return mesh;};
    box([.2,.19,.5],[0,0,.03],body);box([.23,.13,.42],[0,.015,.36],dark,[.08,0,0]);box([.18,.08,.34],[0,.135,.35],body);box([.16,.14,.27],[0,-.025,-.33],dark);box([.12,.23,.16],[0,-.19,.09],dark,[-.2,0,0]);box([.11,.25,.13],[0,-.2,-.14],body,[.12,0,0]);
    box([.215,.025,.43],[0,.105,-.24],accent);cylinder(.035,.78,[0,.035,-.77],steel,14);cylinder(.057,.13,[0,.035,-1.2],dark,12);cylinder(.068,.045,[0,.035,-1.29],steel,12);
    cylinder(.075,.48,[0,.205,-.2],dark,14);cylinder(.08,.055,[0,.205,-.47],steel,14);cylinder(.084,.06,[0,.205,.07],steel,14);cylinder(.064,.012,[0,.205,-.503],lens,16);box([.035,.12,.06],[-.055,.105,-.32],steel);box([.035,.12,.06],[-.055,.105,-.05],steel);
    const bolt=cylinder(.018,.16,[.14,.055,-.08],steel,9);bolt.rotation.z=Math.PI/2;box([.045,.045,.21],[.1,.055,-.08],steel);box([.025,.08,.5],[-.105,.02,-.02],accent);
    this.gunMuzzle.position.set(0,.035,-1.34);this.gun.add(this.gunMuzzle);this.gun.position.set(.34,-.3,-.55);this.gun.rotation.set(0,0,0);this.gun.traverse(object=>{object.frustumCulled=false;object.renderOrder=20;});
    const forearm=new THREE.Mesh(new THREE.CylinderGeometry(.055,.08,.46,10),glove);forearm.position.set(0,-.23,.08);forearm.rotation.z=-.16;const palm=new THREE.Mesh(new THREE.BoxGeometry(.14,.12,.18),glove);palm.position.set(0,.01,-.1);const knuckles=new THREE.Mesh(new THREE.BoxGeometry(.16,.09,.1),dark);knuckles.position.set(0,.07,-.18);this.meleeArm.add(forearm,palm,knuckles);this.meleeArm.visible=false;this.meleeArm.traverse(object=>{object.frustumCulled=false;object.renderOrder=21;});this.camera.add(this.gun,this.meleeArm);
  }
  loop=()=>{requestAnimationFrame(this.loop);const dt=Math.min(this.clock.getDelta(),.033);this.update(dt);this.renderer.render(this.scene,this.camera)};
  storyTutorialIntro(){this.menu.hide();this.story.play(STORIES.tutorialIntro,()=>this.startTutorial());}
  startTutorial(){this.mode='PLAYING';this.menu.hide();this.pos.set(0,CFG.eyeHeight,8);this.vel.set(0,0,0);this.yaw=0;this.pitch=0;this.ammo=CFG.magazine;this.reloading=0;this.sound.stopReload();this.grappleAirborne=false;this.ready();this.tutorial.start();this.input.lock();}
  completeTutorial(){this.progress.tutorialComplete=true;saveProgress(this.progress);this.mode='MENU';if(document.pointerLockElement)document.exitPointerLock();this.dummy.kill();this.menu.refreshProgress(this.progress);this.story.play(STORIES.tutorialOutro,()=>this.menu.showStages());}
  openStage(stage:2|3|4){this.menu.hide();if(stage===2){this.activateStage2World();this.mode='STAGE2_INTRO';this.stage2.enter();return;}if(stage===3){this.activateStage3World();this.mode='STAGE3_INTRO';this.stage3.enter();return;}this.activateStage4World();this.mode='STAGE4_INTRO';this.stage4.enter();}
  activateStage2World(){for(const o of this.phase1Obstacles)o.mesh.visible=false;this.arena.obstacles=this.stage2.map.obstacles;this.arena.grappleMeshes=this.stage2.map.grappleMeshes;this.tutorial.hide();this.dummy.kill();}
  activateStage3World(){for(const o of this.phase1Obstacles)o.mesh.visible=false;this.arena.obstacles=this.stage3.obstacles();this.arena.grappleMeshes=this.stage3.grappleMeshes();this.tutorial.hide();this.dummy.kill();}
  activateStage4World(){for(const o of this.phase1Obstacles)o.mesh.visible=false;this.arena.obstacles=this.stage4.obstacles();this.arena.grappleMeshes=this.stage4.grappleMeshes();this.tutorial.hide();this.dummy.kill();}
  restorePhase1World(){this.stage2.leave();this.stage3.leave();this.stage4.leave();for(const o of this.phase1Obstacles)o.mesh.visible=true;this.arena.obstacles=this.phase1Obstacles;this.arena.grappleMeshes=this.phase1GrappleMeshes;}
  respawnStage2(){this.pos.copy(STAGE2.start);this.camera.position.copy(this.pos);this.vel.set(0,0,0);this.yaw=0;this.pitch=0;this.zoom=0;this.input.zoom=false;this.camera.rotation.set(0,0,0,'YXZ');this.camera.fov=75;this.camera.updateProjectionMatrix();this.scope.classList.remove('on');this.reloading=0;this.sound.stopReload();this.melee=0;this.ammo=CFG.magazine;this.grappleAirborne=false;this.ready();}
  respawnStage3(){this.pos.copy(STAGE3.start);this.camera.position.copy(this.pos);this.vel.set(0,0,0);this.yaw=0;this.pitch=0;this.zoom=0;this.input.zoom=false;this.camera.rotation.set(0,0,0,'YXZ');this.camera.fov=75;this.camera.updateProjectionMatrix();this.scope.classList.remove('on');this.reloading=0;this.sound.stopReload();this.melee=0;this.ammo=CFG.magazine;this.grappleAirborne=false;this.ready();}
  respawnStage4(){this.pos.copy(STAGE4.start);this.camera.position.copy(this.pos);this.vel.set(0,0,0);this.yaw=0;this.pitch=0;this.zoom=0;this.input.zoom=false;this.camera.rotation.set(0,0,0,'YXZ');this.camera.fov=75;this.camera.updateProjectionMatrix();this.scope.classList.remove('on');this.reloading=0;this.sound.stopReload();this.melee=0;this.ammo=CFG.magazine;this.grappleAirborne=false;this.ready();}
  stage4Sound(cue:Stage4Sound){if(cue==='RAIL_CHARGE')this.sound.bossRailCharge();else if(cue==='RAIL_FIRE')this.sound.bossRailFire();else if(cue==='SLAM_CHARGE')this.sound.bossSlamCharge();else if(cue==='SLAM_IMPACT')this.sound.bossSlamImpact();else if(cue==='WAVE_CHARGE')this.sound.bossFloorCharge();else if(cue==='WAVE_IMPACT')this.sound.bossFloorImpact();else if(cue==='MISSILE_LAUNCH')this.sound.bossMissileLaunch();else this.sound.bossMissileExplosion();}
  playerDamaged(){this.sound.playerHit();this.damageVignette.classList.remove('active');void this.damageVignette.offsetWidth;this.damageVignette.classList.add('active');}
  beginReload(){if(this.ammo>=CFG.magazine||this.reloading>0)return;this.reloading=CFG.reload;this.sound.setReloadActive(true);}
  stage2Cleared(record:Stage2Record){this.mode='STAGE2_CLEAR';this.vel.set(0,0,0);this.ready();if(document.pointerLockElement)document.exitPointerLock();addStage2Record(this.progress,record);this.menu.refreshProgress(this.progress);this.story.play(STORIES.stage2Outro,()=>this.stage2.ui.showResult(this.stage2.stats));}
    stage3Finished(result:Stage3Result){this.mode=result.clear?'STAGE3_CLEAR':'STAGE3_FAILED';this.vel.set(0,0,0);this.ready();if(!result.clear)this.sound.failure();if(document.pointerLockElement)document.exitPointerLock();if(result.clear){addStage3Record(this.progress,{score:result.score,kills:result.kills,accuracy:result.accuracy,siegeKills:result.siegeKills,crystalHP:result.crystalHP,shotsFired:result.shotsFired});this.story.play(STORIES.stage3Outro,()=>this.stage3.ui.showResult(result));}this.menu.refreshProgress(this.progress);}
  leaveStage2(){this.restorePhase1World();this.mode='MENU';if(document.pointerLockElement)document.exitPointerLock();this.menu.showStages();}
  leaveStage3(){this.restorePhase1World();this.mode='MENU';if(document.pointerLockElement)document.exitPointerLock();this.menu.showStages();}
  advanceStage(from:2|3){if(document.pointerLockElement)document.exitPointerLock();if(from===2){this.stage2.leave();this.openStage(3);}else{this.stage3.leave();this.openStage(4);}}
  stage4Finished(result:Stage4Result){this.mode=result.clear?'STAGE4_CLEAR':'STAGE4_FAILED';this.vel.set(0,0,0);this.ready();if(!result.clear)this.sound.failure();if(document.pointerLockElement)document.exitPointerLock();if(result.clear){completeStage4(this.progress);this.story.play(STORIES.stage4Outro,()=>this.stage4.ui.showResult(result));}this.menu.refreshProgress(this.progress);}
  leaveStage4(){this.restorePhase1World();this.mode='MENU';if(document.pointerLockElement)document.exitPointerLock();this.menu.showStages();}
  showStage4Thanks(){this.restorePhase1World();this.mode='MENU';if(document.pointerLockElement)document.exitPointerLock();this.menu.showThanks(()=>this.menu.showStages());}
  returnToMain(){if(this.mode.startsWith('STAGE'))this.restorePhase1World();this.mode='MENU';this.vel.set(0,0,0);this.ready();this.tutorial.hide();this.dummy.kill();if(document.pointerLockElement)document.exitPointerLock();this.menu.showMain();}
  update(dt:number){
    const playable=this.mode==='PLAYING'||this.mode==='STAGE2_PLAYING'||this.mode==='STAGE3_PLAYING'||this.mode==='STAGE4_PLAYING';const hint=document.querySelector<HTMLElement>('#hint')!;hint.style.display='none';document.querySelector<HTMLElement>('#pause-menu')!.style.display=playable&&!this.input.locked?'grid':'none';document.querySelector<HTMLElement>('#reset')!.style.display=this.mode==='PLAYING'?'block':'none';this.sound.setBgmActive(playable&&this.input.locked);this.sound.setReloadActive(playable&&this.input.locked&&this.reloading>0);if(this.mode==='STAGE2_PLAYING'&&!this.input.locked)this.stage2.update(this.pos,true);if(this.mode==='STAGE3_PLAYING'&&!this.input.locked)this.stage3.update(this.pos,this.vel,dt,true);if(this.mode==='STAGE4_PLAYING'&&!this.input.locked)this.stage4.update(this.pos,dt,true);if(!playable||!this.input.locked){this.input.endFrame();return;}const zoomFovScale=Math.tan(THREE.MathUtils.degToRad(this.camera.fov*.5))/Math.tan(THREE.MathUtils.degToRad(75*.5));const zoomUserScale=THREE.MathUtils.lerp(1,ZOOM_SENSITIVITY[this.settings.zoomMouse],this.zoom);const sensitivity=MOUSE_SENSITIVITY[this.settings.mouse]*zoomFovScale*zoomUserScale;this.yaw-=this.input.look.x*sensitivity;this.pitch=THREE.MathUtils.clamp(this.pitch-this.input.look.y*sensitivity,-1.52,1.52);this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');
    if(this.mode==='PLAYING'&&this.input.take('KeyT'))this.dummy.reset();if(this.mode==='STAGE2_PLAYING'&&this.input.take('KeyP')){this.respawnStage2();this.stage2.lastPosition.copy(STAGE2.start);this.stage2.ui.respawn();}if(this.mode==='STAGE3_PLAYING'&&this.input.take('KeyP'))this.respawnStage3();if(this.mode==='STAGE4_PLAYING'&&this.input.take('KeyP'))this.respawnStage4();if(this.input.take('KeyR'))this.beginReload();
    for(const code of ['KeyW','KeyA','KeyS','KeyD'])if(this.input.down(code))this.tutorial.key(code);if(this.input.take('ShiftLeft')&&this.grapple==='READY')this.fireGrapple();if(this.input.take('Space')){this.tutorial.key('Space');if(this.grapple==='FIRING'){}else if((this.grapple==='PULLING'||this.grapple==='HOLDING')&&this.pullElapsed>=CFG.pullCancelDelay){this.tutorial.grappleReleased();this.release();}else if(this.grapple==='READY'&&this.grounded){this.vel.y=Math.sqrt(-2*CFG.gravity*CFG.jumpHeight);this.grounded=false;}}
    this.zoom=THREE.MathUtils.clamp(this.zoom+(this.input.zoom?1:-1)*dt/CFG.zoomDuration,0,1);this.camera.fov=75+(75/CFG.zoomMagnification-75)*this.zoom;this.camera.updateProjectionMatrix();this.scope.classList.toggle('on',this.zoom>.95);
    if(this.input.takeMouse(0)){if(this.zoom>.98)this.shoot();else if(this.zoom<=0&&!this.input.zoom)this.startMelee();}
    this.fireCd=Math.max(0,this.fireCd-dt);if(this.reloading>0){this.reloading=Math.max(0,this.reloading-dt);if(this.reloading===0){this.ammo=CFG.magazine;this.sound.stopReload();}}this.updateGrapple(dt);this.move(dt);this.sound.updateFootsteps(dt,this.grounded,Math.hypot(this.vel.x,this.vel.z));if(this.mode==='STAGE2_PLAYING')this.stage2.update(this.pos);if(this.mode==='STAGE3_PLAYING')this.stage3.update(this.pos,this.vel,dt);if(this.mode==='STAGE4_PLAYING')this.stage4.update(this.pos,dt);this.updateCombat(dt);this.tutorial.update(this.pos,dt);this.updateUI(dt);this.input.endFrame();
  }
  move(dt:number){const f=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw)),r=new THREE.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw));const wish=new THREE.Vector3();if(this.input.down('KeyW'))wish.add(f);if(this.input.down('KeyS'))wish.sub(f);if(this.input.down('KeyD'))wish.add(r);if(this.input.down('KeyA'))wish.sub(r);if(wish.lengthSq())wish.normalize().multiplyScalar(CFG.moveSpeed*(this.melee?0.75:1));
    if(this.grapple==='HOLDING'){this.vel.set(0,0,0);this.camera.position.copy(this.pos);return;}if(this.grapple!=='PULLING'){const accel=this.grounded?(wish.lengthSq()?CFG.groundAccel:CFG.groundDecel):(wish.lengthSq()?CFG.airAccel:CFG.airDecel);const h=new THREE.Vector2(this.vel.x,this.vel.z),t=new THREE.Vector2(wish.x,wish.z),d=t.sub(h);if(d.length()>accel*dt)d.setLength(accel*dt);this.vel.x+=d.x;this.vel.z+=d.y;const gravityMultiplier=this.grappleReleaseAscent&&this.vel.y>0?CFG.grappleReleaseAscentGravityMultiplier:1;this.vel.y=Math.max(CFG.maxFall,this.vel.y+CFG.gravity*gravityMultiplier*dt);if(this.grappleReleaseAscent&&this.vel.y<=0)this.grappleReleaseAscent=false;}
    const pulling=this.grapple==='PULLING',pullSpeedBefore=pulling?this.vel.length():0,wasGrounded=this.grounded,impactSpeed=Math.max(0,-this.vel.y);let pullCollision=false;const next=this.pos.clone().addScaledVector(this.vel,dt);this.grounded=false;const feet=next.y-CFG.eyeHeight;
    if(feet<0){next.y=CFG.eyeHeight;if(this.vel.y<0){this.vel.y=0;pullCollision=true;}this.grounded=true;}
    const stageCollision=this.mode==='STAGE2_PLAYING'||this.mode==='STAGE3_PLAYING'||this.mode==='STAGE4_PLAYING';const collisionObstacles=stageCollision?this.arena.obstacles:this.arena.obstacles.slice(1);for(const o of collisionObstacles){const b=o.box.clone();b.min.x-=CFG.playerRadius;b.max.x+=CFG.playerRadius;b.min.z-=CFG.playerRadius;b.max.z+=CFG.playerRadius;const y0=next.y-CFG.eyeHeight,y1=y0+CFG.playerHeight;if(next.x>b.min.x&&next.x<b.max.x&&next.z>b.min.z&&next.z<b.max.z&&y1>b.min.y&&y0<b.max.y){pullCollision=true;const currentFeet=this.pos.y-CFG.eyeHeight,currentHead=currentFeet+CFG.playerHeight,stepHeight=b.max.y-currentFeet;if((this.mode==='STAGE3_PLAYING'||this.mode==='STAGE4_PLAYING')&&this.vel.y<=0&&stepHeight>0&&stepHeight<=.45){next.y=b.max.y+CFG.eyeHeight;this.vel.y=0;this.grounded=true;}else if(this.vel.y>0&&currentHead<=b.min.y+.12){next.y=b.min.y-(CFG.playerHeight-CFG.eyeHeight);this.vel.y=0;}else if(this.vel.y<=0&&currentFeet>=b.max.y-.12){next.y=b.max.y+CFG.eyeHeight;this.vel.y=0;this.grounded=true;}else{const dx=Math.min(Math.abs(next.x-b.min.x),Math.abs(b.max.x-next.x)),dz=Math.min(Math.abs(next.z-b.min.z),Math.abs(b.max.z-next.z));if(dx<dz){next.x=this.pos.x;this.vel.x=0}else{next.z=this.pos.z;this.vel.z=0}}}}
    if(this.mode==='STAGE4_PLAYING'){const radius=Math.hypot(next.x,next.z),limit=STAGE4.arenaRadius-CFG.playerRadius-.85;if(radius>limit){const nx=next.x/radius,nz=next.z/radius;next.x=nx*limit;next.z=nz*limit;const outward=this.vel.x*nx+this.vel.z*nz;if(outward>0){this.vel.x-=nx*outward;this.vel.z-=nz*outward;}pullCollision=true;}}
    if(pulling&&pullCollision){if(this.vel.lengthSq()<.01)this.release();else this.vel.setLength(pullSpeedBefore);}
    this.pos.copy(next);if(!wasGrounded&&this.grounded&&impactSpeed>1.5)this.sound.land(impactSpeed);if(this.grounded&&this.grapple!=='PULLING')this.grappleAirborne=false;this.camera.position.copy(this.pos);const speed=Math.hypot(this.vel.x,this.vel.z);this.viewBob=Math.sin(performance.now()*.012)*.008*Math.min(speed/CFG.moveSpeed,1);
  }
  fireGrapple(){if(this.grapple!=='READY')return;this.sound.grappleFire();this.grapple='FIRING';this.grappleHitObject=null;this.hookStart.copy(this.pos);this.hook.position.copy(this.pos);this.camera.getWorldDirection(this.hookDir);this.hook.visible=this.rope.visible=true;this.grappleDistance=0;this.lastGrappleDistance=Infinity;this.grappleStallTime=0;this.ray.set(this.pos,this.hookDir);this.ray.far=CFG.grappleRange;const stageTargets=this.mode==='STAGE2_PLAYING'?this.stage2.hitObjects():this.mode==='STAGE3_PLAYING'?this.stage3.hitObjects():[];const hits=this.ray.intersectObjects([...this.arena.grappleMeshes,...stageTargets,...(this.dummy.alive?[this.dummy.head,this.dummy.body]:[])],false);if(hits.length){this.grappleTarget.copy(hits[0].point);this.grappleDistance=hits[0].distance;const hit=hits[0].object;if(hit===this.dummy.head||hit===this.dummy.body||hit.userData.stage2Target||hit.userData.stage3Enemy){this.grappleHitObject=hit;this.grappleSurface='ENEMY';}else{const n=hits[0].face?.normal.clone().transformDirection(hit.matrixWorld)??new THREE.Vector3(0,1,0);this.grappleNormal.copy(n);this.grappleSurface=n.y>.65?'GROUND':n.y<-.65?'CEILING':'WALL';}}else{this.grappleTarget.copy(this.pos).addScaledVector(this.hookDir,CFG.grappleRange);this.grappleNormal.copy(this.hookDir).negate();this.grappleDistance=CFG.grappleRange;this.grappleSurface='MISS';}}
  colliderDistanceTo(point:THREE.Vector3){const feetY=this.pos.y-CFG.eyeHeight;const low=feetY+CFG.playerRadius;const high=feetY+CFG.playerHeight-CFG.playerRadius;const closestY=THREE.MathUtils.clamp(point.y,low,high);return Math.max(0,new THREE.Vector3(this.pos.x,closestY,this.pos.z).distanceTo(point)-CFG.playerRadius);}
  desiredEyePosition(_withAutoHop=false){let clearance=CFG.playerRadius+.1;if(this.grappleSurface==='GROUND')clearance=CFG.eyeHeight;else if(this.grappleSurface==='CEILING')clearance=CFG.playerHeight-CFG.eyeHeight+.1;return this.grappleTarget.clone().addScaledVector(this.grappleNormal,clearance);}
  animateViewmodel(){
    const ease=(value:number)=>value*value*(3-2*value),progress=this.melee?THREE.MathUtils.clamp(1-this.melee/CFG.meleeDuration,0,1):0;
    const gunShift=!this.melee?0:progress<.18?ease(progress/.18):progress<.72?1:1-ease((progress-.72)/.28);
    const thrust=!this.melee?0:progress<.16?0:progress<.38?ease((progress-.16)/.22):progress<.58?1:progress<.82?1-ease((progress-.58)/.24):0;
    this.gun.position.set(.34+gunShift*.22,-.3+this.viewBob-gunShift*.09,-.55+this.gunRecoil+gunShift*.07);this.gun.rotation.set(-gunShift*.1,gunShift*.38,gunShift*.43);
    this.meleeArm.visible=this.melee>0;if(this.meleeArm.visible){this.meleeArm.position.set(THREE.MathUtils.lerp(-.43,-.07,thrust),THREE.MathUtils.lerp(-.49,-.15,thrust),THREE.MathUtils.lerp(-.34,-.96,thrust));this.meleeArm.rotation.set(-.12+thrust*.24,-.28+thrust*.16,-.5+thrust*.42);}
  }
  beginPull(){this.sound.grappleAttach();this.grapple='PULLING';this.grappleAirborne=true;this.tutorial.grappleAttached();this.arrivalTime=0;this.pullElapsed=0;this.grappleStallTime=0;this.lastGrappleDistance=Infinity;this.autoHop=this.grounded&&this.grappleSurface==='GROUND';this.autoHopVerticalVelocity=this.autoHop?Math.sqrt(-2*CFG.gravity*CFG.autoHopHeight):0;const direction=this.desiredEyePosition().sub(this.pos).normalize();this.vel.copy(direction).multiplyScalar(CFG.pullMinSpeed);this.vel.y+=this.autoHopVerticalVelocity;this.grounded=false;}
  updateGrapple(dt:number){if(this.grapple==='FIRING'){const remain=this.hook.position.distanceTo(this.grappleTarget);const step=CFG.hookSpeed*dt;if(step>=remain){this.hook.position.copy(this.grappleTarget);if(this.grappleSurface==='MISS'){this.grapple='MISSED';this.arrivalTime=.14}else if(this.grappleSurface==='ENEMY'){this.sound.grappleAttach();this.sound.hit();if(this.grappleHitObject?.userData.stage2Target)this.stage2.hitObject(this.grappleHitObject,'HOOK');else if(this.grappleHitObject?.userData.stage3Enemy)this.stage3.hitObject(this.grappleHitObject,'HOOK');else this.dummy.kill();this.grapple='ENEMY_HIT';this.arrivalTime=.18}else this.beginPull();}else this.hook.position.lerp(this.grappleTarget,step/remain);}else if(this.grapple==='PULLING'){this.pullElapsed+=dt;const finalEye=this.desiredEyePosition();const dist=this.pos.distanceTo(finalEye);this.grappleDistance=dist;if(dist<CFG.arrival){this.pos.copy(finalEye);this.camera.position.copy(finalEye);this.grappleDistance=0;this.grapple='HOLDING';this.arrivalTime=CFG.arrivalHold;this.autoHopVerticalVelocity=0;this.vel.set(0,0,0);}else{if(this.autoHop&&this.pullElapsed<.35)this.grappleStallTime=0;else if(this.lastGrappleDistance-dist<.005)this.grappleStallTime+=dt;else this.grappleStallTime=0;this.lastGrappleDistance=dist;if(this.grappleStallTime>.15){this.release();}else{const direction=this.desiredEyePosition().sub(this.pos).normalize();const pullSpeed=Math.min(CFG.pullMaxSpeed,CFG.pullMinSpeed+CFG.pullAccel*this.pullElapsed);this.vel.copy(direction).multiplyScalar(pullSpeed);if(this.autoHopVerticalVelocity>0){this.vel.y+=this.autoHopVerticalVelocity;this.autoHopVerticalVelocity=Math.max(0,this.autoHopVerticalVelocity+CFG.gravity*dt);}}}}else if(this.grapple==='HOLDING'){this.pullElapsed+=dt;this.arrivalTime-=dt;if(this.arrivalTime<=0)this.release();}else if(this.grapple!=='READY'){this.arrivalTime-=dt;if(this.arrivalTime<=0)this.ready();}if(this.rope.visible)this.rope.geometry.setFromPoints([this.pos.clone().add(new THREE.Vector3(.2,-.18,0)),this.hook.position]);}
  release(){this.grappleReleaseAscent=this.vel.y>0;this.grapple='RELEASED';this.arrivalTime=.08;this.autoHop=false;this.autoHopVerticalVelocity=0;}ready(){this.grapple='READY';this.hook.visible=this.rope.visible=false;this.grappleSurface='NONE';}
  shoot(){if(this.fireCd||this.reloading>0)return;if(!this.ammo){this.input.zoom=false;this.zoom=0;this.beginReload();return;}this.ammo--;this.sound.rifle();this.fireCd=CFG.fireInterval;if(this.mode==='STAGE2_PLAYING')this.stage2.stats.shot();if(this.mode==='STAGE3_PLAYING')this.stage3.shot();if(this.mode==='STAGE4_PLAYING')this.stage4.shot();this.ray.setFromCamera(new THREE.Vector2(),this.camera);this.ray.far=100;const tutorialTargets=this.dummy.alive?[this.dummy.head,this.dummy.body]:[],stageTargets=this.mode==='STAGE2_PLAYING'?this.stage2.hitObjects():this.mode==='STAGE3_PLAYING'?this.stage3.hitObjects():this.mode==='STAGE4_PLAYING'?this.stage4.hitObjects():[],targets=[...tutorialTargets,...stageTargets],bulletSurfaces=this.arena.grappleMeshes.filter(object=>!object.userData.ignoreBullets);const hits=this.ray.intersectObjects([...targets,...bulletSurfaces],false);const end=hits[0]?.point??this.ray.ray.at(100,new THREE.Vector3());if(hits[0]&&targets.includes(hits[0].object as THREE.Mesh)){if(hits[0].object.userData.stage2Target)this.stage2.hitObject(hits[0].object);else if(hits[0].object.userData.stage3Enemy)this.stage3.hitObject(hits[0].object,'SHOT');else if(hits[0].object.userData.stage4Weakpoint)this.stage4.hitObject(hits[0].object);else if(!hits[0].object.userData.stage4BossBlocker){this.dummy.kill();this.tutorial.dummyKilled('SHOT',!this.grounded&&this.grappleAirborne);}this.sound.hit();}const start=this.gunMuzzle.getWorldPosition(new THREE.Vector3()),line=createTracerBeam(start,end,0xfff4f4,.018,1);this.scene.add(line);this.tracers.push({line,life:CFG.tracerLifetime});this.gunRecoil=.11;}
  startMelee(){if(this.melee||this.grapple==='FIRING'||this.grapple==='PULLING'||this.grapple==='HOLDING')return;this.melee=CFG.meleeDuration;}
  updateCombat(dt:number){
    const old=this.melee;if(this.melee){this.melee=Math.max(0,this.melee-dt);const elapsed=CFG.meleeDuration-this.melee;if(old===CFG.meleeDuration||elapsed>=CFG.meleeHitStart&&elapsed-dt<CFG.meleeHitStart){const f=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw));if(this.mode==='STAGE2_PLAYING')this.stage2.melee(this.pos,f,CFG.meleeRange,THREE.MathUtils.degToRad(CFG.meleeAngle/2));else if(this.mode==='STAGE3_PLAYING')this.stage3.melee(this.pos,f,CFG.meleeRange,THREE.MathUtils.degToRad(CFG.meleeAngle/2));else{const to=this.dummy.group.position.clone().sub(this.pos);to.y=0;if(this.dummy.alive&&to.length()<CFG.meleeRange&&f.angleTo(to.normalize())<THREE.MathUtils.degToRad(CFG.meleeAngle/2)){this.dummy.kill();this.tutorial.dummyKilled('MELEE',false);}}}}
    this.gunRecoil=THREE.MathUtils.lerp(this.gunRecoil,0,Math.min(1,dt*18));this.animateViewmodel();for(const t of this.tracers){t.life-=dt;t.line.material.opacity=Math.max(0,t.life/CFG.tracerLifetime);}for(const t of this.tracers.filter(x=>x.life<=0)){this.scene.remove(t.line);t.line.geometry.dispose();t.line.material.dispose();}this.tracers=this.tracers.filter(x=>x.life>0);
  }
  updateUI(dt:number){this.frames++;this.fpsTime+=dt;if(this.fpsTime>.5){this.fps=this.frames/this.fpsTime;this.frames=0;this.fpsTime=0;}const speed=this.vel.length(),stageDebug=this.mode.startsWith('STAGE3')?`\n${this.stage3.debugText()}`:this.mode.startsWith('STAGE4')?`\n${this.stage4.debugText()}`:'';this.hud.update(`FPS ${this.fps.toFixed(0)}\nPOS ${this.pos.x.toFixed(2)} / ${(this.pos.y-CFG.eyeHeight).toFixed(2)} / ${this.pos.z.toFixed(2)}\nVEL ${this.vel.x.toFixed(2)} / ${this.vel.y.toFixed(2)} / ${this.vel.z.toFixed(2)}  (${speed.toFixed(2)} m/s)\nGROUNDED ${this.grounded}  NORMAL ${this.grounded?'0,1,0':'—'}\nMOVEMENT ${this.grapple==='PULLING'?'GRAPPLE':this.grounded?'GROUNDED':'AIRBORNE'}\nGRAPPLE ${this.grapple}  ${this.grappleDistance.toFixed(1)}m\nSURFACE ${this.grappleSurface}  AUTO-HOP ${this.autoHop}\nZOOM ${this.zoom>.98?'ZOOMED':this.zoom>0?'ZOOMING':'UNZOOMED'}\nAMMO ${this.ammo}/${CFG.magazine} ${this.reloading?'RELOADING':''}${stageDebug}`,this.input.locked?'':'CLICK TO CAPTURE MOUSE');this.ammoEl.textContent=this.reloading?'RELOADING':`${this.ammo} / ${CFG.magazine}`;this.grappleEl.textContent=`GRAPPLE // ${this.grapple}`;}
}
